site: 
  title: Documentation
  url: http://petrel.local
content:
  sources: 
  - url: ~/github/Kineviz/kineviz-docs/
    start_path: GraphXR-WEB/asciidoc/3-x
  - url: ~/github/Kineviz/kineviz-docs/
    start_path: GraphXR-WEB/asciidoc/2-x
ui:
  bundle:
    url: ./ui-bundle-Nov30.zip
    snapshot: true
antora:
  extensions:
  - require: '@antora/lunr-extension'